### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by memelopez** [hendridg/todo-list#4]
https://github.com/hendridg/todo-list/blob/da3262e6255b0a4e46f02c41aadd63aef2023bc1/webpack.config.js#L6

es necesario agregar tosdos los archivos al entry aqui?

**Comment by hendridg** [comment]
Hola @memelopez , Si instalas el plugin `HtmlWebpackPlugin` el te generencia el `input `y el `output`

```javascript
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: {
    index: './src/index.js',
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.html',
    }),
  ],
```
De esta forma el plugin te genera las salidas, y tienes que colocar la salida de esta forma para que funcione

```javascript
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist'),
    clean: true,
  },
```

Alli el plugin te va a manejar los modulos de tu proyecto de forma automatica, quitandote el peso de estar pendiente tu de cada modulo que crees.
